version: '3.3'

networks:
  ezekiel:

services:
  ezekiel-web:
    image: 'nginx:stable-alpine'
    container_name: "ezekiel-NTI4MAo-web"
    restart: always
    depends_on:
      - ezekiel-db
      - ezekiel-fpm
    volumes:
      - .:/app
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ./logs/nginx:/var/log/nginx
    ports:
      - 1440:80
    networks:
      - ezekiel

  ezekiel-db:
    image: postgres:12.1
    container_name: "ezekiel-NTI4MAo-db"
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - 5432
    volumes:
      - ./setup/database/db.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ezekiel

  ezekiel-fpm:
    image: adriel/boilerplate-php-fpm
    container_name: "ezekiel-NTI4MAo-fpm"
    hostname: nginx-fpm-host
    volumes:
      - .:/app
      - ./logs/php:/var/log/php-fpm
    expose:
      - 9000
    networks:
      - ezekiel
