- name: Publish
  hosts: all
  become: true
  become_user: adriel
  become_method: su

  vars:
    date: "{{ lookup('pipe', 'date +%Y-%m-%d-%H-%M') }}"

  tasks:
    - ping: ~

    - name: Determine whether code is pushed already
      become: false
      command: git diff --exit-code
      delegate_to: localhost
      args:
        chdir: "{{ playbook_dir }}/../../"
      register: need_to_push
      failed_when: need_to_push.rc != 1 and need_to_push.rc != 0

    - name: Push local code to Github
      become: false
      command: "{{ item }}"
      delegate_to: localhost
      args:
        chdir: "{{ playbook_dir }}/../../"
      with_items:
        - git add .
        - git commit -m "Publish new version"
        - git push -u origin master
      when:
        - need_to_push.rc != 0

    - name: Compress and move previous "current" code into "versions"
      community.general.archive:
        path:
          - /var/www/html/{{ project_name }}/current/app
          - /var/www/html/{{ project_name }}/current/native
          - /var/www/html/{{ project_name }}/current/composer.json
          - /var/www/html/{{ project_name }}/current/composer.lock
          - /var/www/html/{{ project_name }}/current/ezekiel
        dest: /var/www/html/{{ project_name }}/versions/latest.tar.gz

    - name: Rename brand new "latest.tar.gz" into a date-formatted filename
      command: "mv latest.tar.gz version-{{ date }}.tar.gz"
      args:
        chdir: /var/www/html/{{ project_name }}/versions

    - name: Pull code remotely from Github
      become: true
      become_user: root
      git:
        repo: "{{ git_repository_url }}"
        dest: /var/www/html/{{ project_name }}/current
        update: yes
        force: yes
        version: master

    - name: Install dependencies
      command: composer install
      args:
        chdir: /var/www/html/{{ project_name }}/current/

    - name: Update dotenv configuration
      copy:
        src: "{{ playbook_dir }}/../../configuration/.production.env"
        dest: /var/www/html/{{ project_name }}/current/configuration/.custom.env

    - name: Run migrations
      command: ./ezekiel run:migrations
      args:
        chdir: /var/www/html/{{ project_name }}/current

    - name: Run bundle
      command: ./ezekiel run:bundle
      become: yes
      become_user: root
      args:
        chdir: /var/www/html/{{ project_name }}/current

    - name: Run invalidate
      command: ./ezekiel run:invalidate
      become: yes
      become_user: root
      args:
        chdir: /var/www/html/{{ project_name }}/current

    - name: Find all previous versions
      find:
        path: /var/www/html/{{ project_name }}/versions
      register: versions

    - name: Keep only the 5 last releases
      file:
        path: "{{ item.path }}"
        state: absent
      with_items:
        - "{{ (versions.files | sort(attribute='ctime'))[:-5] }}"

